import type { Challenge } from '@english-practice/shared';

/** Semilla versionada de desafíos. Se carga (upsert) en cada arranque. */
export const CHALLENGE_SEED: Challenge[] = [
  {
    id: 'work-email-time-off-b1',
    context: 'work_email',
    prompt: 'Write an email to your manager requesting time off',
    description: 'Explica las fechas, el motivo y cómo cubrirás tus tareas mientras no estés. Tono formal.',
    level: 'B1',
    minWords: 80,
    maxWords: 120,
    register: 'formal',
    timeLimitSeconds: 720,
  },
  {
    id: 'work-email-meeting-reschedule-b2',
    context: 'work_email',
    prompt: 'Write an email to a client asking to reschedule a meeting',
    description: 'Pide disculpas por el cambio, propón dos alternativas concretas y confirma cómo seguir. Tono formal y cordial.',
    level: 'B2',
    minWords: 100,
    maxWords: 150,
    register: 'formal',
    timeLimitSeconds: 900,
  },
  {
    id: 'work-email-status-update-a2',
    context: 'work_email',
    prompt: 'Write a short email to your team with an update on your project',
    description: 'Cuenta qué terminaste esta semana, qué falta y si necesitas ayuda. Frases simples y claras.',
    level: 'A2',
    minWords: 50,
    maxWords: 90,
    register: 'formal',
    timeLimitSeconds: 600,
  },
  {
    id: 'friend-letter-trip-a2',
    context: 'friend_letter',
    prompt: 'Write a message to a friend telling them about your last trip',
    description: 'Cuenta adónde fuiste, qué hiciste y qué fue lo mejor. Tono informal y cercano.',
    level: 'A2',
    minWords: 60,
    maxWords: 100,
    register: 'informal',
    timeLimitSeconds: 600,
  },
  {
    id: 'friend-letter-invite-b1',
    context: 'friend_letter',
    prompt: 'Write a message inviting a friend to visit your city',
    description: 'Propón fechas, sugiere qué podrían hacer juntos y explica dónde se quedaría. Tono informal.',
    level: 'B1',
    minWords: 80,
    maxWords: 120,
    register: 'informal',
    timeLimitSeconds: 720,
  },
  {
    id: 'instructions-recipe-a2',
    context: 'instructions',
    prompt: 'Write simple instructions to prepare your favorite dish',
    description: 'Lista los ingredientes y describe los pasos en orden usando imperativos (cut, mix, add...).',
    level: 'A2',
    minWords: 60,
    maxWords: 100,
    register: 'informal',
    timeLimitSeconds: 600,
  },
  {
    id: 'instructions-onboarding-b2',
    context: 'instructions',
    prompt: 'Write instructions for a new colleague on how to request access to the company systems',
    description: 'Explica los pasos, a quién contactar y qué información deben preparar. Claro, ordenado y formal.',
    level: 'B2',
    minWords: 100,
    maxWords: 150,
    register: 'formal',
    timeLimitSeconds: 900,
  },
  {
    id: 'complaint-product-b1',
    context: 'complaint',
    prompt: 'Write a complaint to an online store about a damaged product',
    description: 'Describe qué compraste, qué llegó mal y qué solución esperas (reembolso o cambio). Firme pero cortés.',
    level: 'B1',
    minWords: 80,
    maxWords: 120,
    register: 'formal',
    timeLimitSeconds: 720,
  },
  {
    id: 'complaint-service-c1',
    context: 'complaint',
    prompt: 'Write a formal complaint to a hotel about the service during your stay',
    description: 'Detalla los problemas, su impacto, y solicita una compensación concreta. Registro formal y argumentación sólida.',
    level: 'C1',
    minWords: 150,
    maxWords: 220,
    register: 'formal',
    timeLimitSeconds: 1200,
  },
  {
    id: 'other-opinion-b2',
    context: 'other',
    prompt: 'Write a short opinion piece: should companies allow remote work every day?',
    description: 'Toma una postura, da dos argumentos con ejemplos y cierra con una conclusión. Registro neutro a formal.',
    level: 'B2',
    minWords: 120,
    maxWords: 180,
    register: 'formal',
    timeLimitSeconds: 1080,
  },
  {
    id: 'other-daily-routine-a1',
    context: 'other',
    prompt: 'Describe your daily routine',
    description: 'Cuenta qué haces en un día normal, desde que te levantas hasta que te acuestas. Presente simple.',
    level: 'A1',
    minWords: 40,
    maxWords: 70,
    register: 'informal',
    timeLimitSeconds: 480,
  },
];
